# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f21784a3fd38f655d5a0eb7d2493b4245c6b55500a623bf11a2efa78f7595d8bc0be354eab8a95f7aaef62609a88504b4cd57dc58d42af5786a53e6ab3d0b375

test:
  secret_key_base: ec3b8ad806e7dd4147f0a46755cba8dccb82ee4f2caa69177013a2d1d728098722527b16ffb3272c5bbcf9de89de350799ed8dbeb0625e16a4a7fe4ba52fd9fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
